-- Torneos: el admin los crea y los conduce; el público ve los publicados y se inscribe por link.
-- Dos formatos: "puntuacion" (rondas con mesas; se anotan puntos por jugador) y "eliminacion" (llave 1 vs 1).
create table public.torneos (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  nombre text not null check (char_length(btrim(nombre)) between 3 and 100),
  -- Si el juego se borra el torneo se conserva.
  juego_id bigint references public.juegos (id) on delete set null,
  descripcion text check (descripcion is null or char_length(descripcion) <= 1000),
  formato text not null check (formato in ('puntuacion', 'eliminacion')),
  fecha timestamptz not null,
  lugar text check (lugar is null or char_length(lugar) <= 120),
  cupos smallint not null check (cupos between 2 and 256),
  rondas smallint check (rondas between 1 and 20),
  tamano_mesa smallint check (tamano_mesa between 2 and 8),
  estado text not null default 'borrador' check (estado in ('borrador', 'inscripcion', 'en_curso', 'finalizado', 'cancelado')),
  ronda_actual smallint not null default 0,
  creado timestamptz not null default now(),
  constraint puntuacion_con_rondas check (formato <> 'puntuacion' or (rondas is not null and tamano_mesa is not null))
);
create index torneos_estado_idx on public.torneos (estado, fecha desc);

create table public.inscripciones (
  id bigint generated by default as identity primary key,
  torneo_id bigint not null references public.torneos (id) on delete cascade,
  nombre text not null check (char_length(btrim(nombre)) between 2 and 80),
  telefono text not null check (telefono ~ '^\+[0-9]{8,15}$'),
  email text check (email is null or (char_length(email) <= 120 and email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')),
  acepta boolean not null check (acepta),
  estado text not null default 'inscrito' check (estado in ('inscrito', 'espera', 'retirado')),
  creado timestamptz not null default now(),
  unique (torneo_id, telefono)
);
create index inscripciones_torneo_idx on public.inscripciones (torneo_id, estado);

-- Una partida es una mesa (puntuación) o un cruce 1 vs 1 (eliminación). En la llave, la partida (ronda, n) alimenta a
-- la (ronda + 1, ceil(n / 2)).
create table public.partidas (
  id bigint generated by default as identity primary key,
  torneo_id bigint not null references public.torneos (id) on delete cascade,
  ronda smallint not null check (ronda >= 1),
  numero smallint not null check (numero >= 1),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'jugada')),
  unique (torneo_id, ronda, numero)
);
create table public.partida_jugadores (
  partida_id bigint not null references public.partidas (id) on delete cascade,
  inscripcion_id bigint not null references public.inscripciones (id) on delete cascade,
  puntos numeric,
  gano boolean,
  primary key (partida_id, inscripcion_id)
);
create index partida_jugadores_inscripcion_idx on public.partida_jugadores (inscripcion_id);

-- Lo que el visitante no decide (estado, fecha, cupo) lo fija el servidor, y se frena el abuso.
create function public.preparar_inscripcion() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  t public.torneos;
begin
  select * into t from public.torneos where id = new.torneo_id;
  if t.id is null or t.estado <> 'inscripcion' then
    raise exception 'Las inscripciones de este torneo no están abiertas.';
  end if;
  new.nombre := btrim(new.nombre);
  new.creado := now();
  new.estado := case
    when (select count(*) from public.inscripciones i where i.torneo_id = new.torneo_id and i.estado = 'inscrito') < t.cupos
    then 'inscrito' else 'espera' end;

  if (select count(*) from public.inscripciones i where i.telefono = new.telefono and i.creado > now() - interval '1 hour') >= 5 then
    raise exception 'Demasiadas inscripciones con este número. Inténtalo más tarde.';
  end if;
  if (select count(*) from public.inscripciones i where i.creado > now() - interval '1 hour') >= 300 then
    raise exception 'Hay demasiadas inscripciones ahora mismo. Inténtalo en unos minutos.';
  end if;
  return new;
end;
$$;
create trigger inscripciones_preparar before insert on public.inscripciones
  for each row execute function public.preparar_inscripcion();

alter table public.torneos enable row level security;
alter table public.inscripciones enable row level security;
alter table public.partidas enable row level security;
alter table public.partida_jugadores enable row level security;

grant select on public.torneos to anon, authenticated;
grant insert, update, delete on public.torneos to authenticated;
grant insert on public.inscripciones to anon, authenticated;
grant select, update, delete on public.inscripciones to authenticated;
grant select, insert, update, delete on public.partidas, public.partida_jugadores to authenticated;
grant usage on sequence public.torneos_id_seq, public.partidas_id_seq to authenticated;
grant usage on sequence public.inscripciones_id_seq to anon, authenticated;

create policy "ver torneos publicados" on public.torneos for select to anon, authenticated
  using (estado <> 'borrador' or public.es_admin());
create policy "admin crea torneos" on public.torneos for insert to authenticated with check (public.es_admin());
create policy "admin edita torneos" on public.torneos for update to authenticated
  using (public.es_admin()) with check (public.es_admin());
create policy "admin borra torneos" on public.torneos for delete to authenticated using (public.es_admin());

-- Los datos personales de las inscripciones son solo del admin; el público ve nombres a través de las vistas de abajo.
create policy "cualquiera se inscribe" on public.inscripciones for insert to anon, authenticated
  with check (acepta and exists (select 1 from public.torneos t where t.id = torneo_id and t.estado = 'inscripcion'));
create policy "admin ve inscripciones" on public.inscripciones for select to authenticated using (public.es_admin());
create policy "admin edita inscripciones" on public.inscripciones for update to authenticated
  using (public.es_admin()) with check (public.es_admin());
create policy "admin borra inscripciones" on public.inscripciones for delete to authenticated using (public.es_admin());

create policy "admin gestiona partidas" on public.partidas for all to authenticated
  using (public.es_admin()) with check (public.es_admin());
create policy "admin gestiona jugadores de partida" on public.partida_jugadores for all to authenticated
  using (public.es_admin()) with check (public.es_admin());

-- Vistas públicas: solo nombres, sin teléfono ni correo, y solo de torneos publicados.
create view public.torneo_participantes with (security_invoker = false) as
  select i.id, i.torneo_id, i.nombre, i.estado
  from public.inscripciones i
  join public.torneos t on t.id = i.torneo_id and t.estado <> 'borrador'
  where i.estado <> 'retirado';
create view public.torneo_partidas_publicas with (security_invoker = false) as
  select p.id as partida_id, p.torneo_id, p.ronda, p.numero, p.estado, pj.inscripcion_id, i.nombre, pj.puntos, pj.gano
  from public.partidas p
  join public.torneos t on t.id = p.torneo_id and t.estado <> 'borrador'
  left join public.partida_jugadores pj on pj.partida_id = p.id
  left join public.inscripciones i on i.id = pj.inscripcion_id;
grant select on public.torneo_participantes, public.torneo_partidas_publicas to anon, authenticated;

-- Crea partidas a partir de un JSON: [{ronda, numero, estado, jugadores: [{inscripcion_id, gano?}]}]. Solo admin.
create function public.crear_partidas(p_torneo bigint, p_partidas jsonb) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not public.es_admin() then
    raise exception 'Solo un administrador puede crear partidas.';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_partidas) x, jsonb_array_elements(coalesce(x -> 'jugadores', '[]'::jsonb)) j
    where not exists (
      select 1 from public.inscripciones i
      where i.id = (j ->> 'inscripcion_id')::bigint and i.torneo_id = p_torneo and i.estado = 'inscrito')
  ) then
    raise exception 'Hay jugadores que no están inscritos en este torneo.';
  end if;

  with nuevas as (
    insert into public.partidas (torneo_id, ronda, numero, estado)
    select p_torneo, (x ->> 'ronda')::smallint, (x ->> 'numero')::smallint, coalesce(x ->> 'estado', 'pendiente')
    from jsonb_array_elements(p_partidas) x
    returning id, ronda, numero
  )
  insert into public.partida_jugadores (partida_id, inscripcion_id, gano)
  select n.id, (j ->> 'inscripcion_id')::bigint, (j ->> 'gano')::boolean
  from jsonb_array_elements(p_partidas) x
  join nuevas n on n.ronda = (x ->> 'ronda')::smallint and n.numero = (x ->> 'numero')::smallint
  cross join lateral jsonb_array_elements(coalesce(x -> 'jugadores', '[]'::jsonb)) j;
end;
$$;

-- Cierra las inscripciones, crea las partidas de la primera ronda y deja el torneo en curso, todo en un solo paso.
create function public.iniciar_torneo(p_torneo bigint, p_partidas jsonb) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not public.es_admin() then
    raise exception 'Solo un administrador puede iniciar un torneo.';
  end if;
  perform 1 from public.torneos where id = p_torneo and estado = 'inscripcion' for update;
  if not found then
    raise exception 'El torneo no está en inscripción.';
  end if;
  perform public.crear_partidas(p_torneo, p_partidas);
  update public.torneos set estado = 'en_curso', ronda_actual = 1 where id = p_torneo;
end;
$$;
revoke execute on function public.crear_partidas(bigint, jsonb), public.iniciar_torneo(bigint, jsonb) from public, anon;
grant execute on function public.crear_partidas(bigint, jsonb), public.iniciar_torneo(bigint, jsonb) to authenticated;
