-- Solicitudes para jugar: un visitante pide un juego que no está en el local y deja su contacto para que le avisen.
-- Cualquiera puede ENVIAR una solicitud; solo los admins pueden VERLAS, cambiarlas o borrarlas (son datos personales).
create table public.solicitudes (
  id bigint generated by default as identity primary key,
  -- Si el juego se borra la solicitud se conserva (con su nombre guardado) en vez de perderse.
  juego_id bigint references public.juegos (id) on delete set null,
  juego_nombre text not null,
  nombre text not null check (char_length(btrim(nombre)) between 2 and 80),
  -- Siempre en formato internacional: la web lo normaliza antes de enviarlo.
  telefono text not null check (telefono ~ '^\+[0-9]{8,15}$'),
  email text check (email is null or (char_length(email) <= 120 and email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')),
  nota text check (nota is null or char_length(nota) <= 300),
  acepta boolean not null check (acepta),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'contactado', 'cancelada')),
  creado timestamptz not null default now(),
  contactado_en timestamptz
);

create index solicitudes_juego_idx on public.solicitudes (juego_id);
create index solicitudes_estado_idx on public.solicitudes (estado, creado desc);
-- Una persona no puede pedir dos veces el mismo juego mientras la primera siga pendiente.
create unique index solicitudes_unica_pendiente on public.solicitudes (juego_id, telefono) where estado = 'pendiente';

-- Lo que el visitante no puede decidir (nombre del juego, estado, fechas) lo fija el servidor, y se frena el abuso.
create function public.preparar_solicitud() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  nombre_juego text;
begin
  select j.nombre into nombre_juego from public.juegos j where j.id = new.juego_id;
  if nombre_juego is null then
    raise exception 'Ese juego no existe.';
  end if;
  new.juego_nombre := nombre_juego;
  new.nombre := btrim(new.nombre);
  new.estado := 'pendiente';
  new.creado := now();
  new.contactado_en := null;

  if (select count(*) from public.solicitudes s where s.telefono = new.telefono and s.estado = 'pendiente') >= 10 then
    raise exception 'Este número ya tiene muchas solicitudes pendientes.';
  end if;
  if (select count(*) from public.solicitudes s where s.telefono = new.telefono and s.creado > now() - interval '1 hour') >= 5 then
    raise exception 'Demasiadas solicitudes con este número. Inténtalo más tarde.';
  end if;
  if (select count(*) from public.solicitudes s where s.creado > now() - interval '1 hour') >= 300 then
    raise exception 'Hay demasiadas solicitudes ahora mismo. Inténtalo en unos minutos.';
  end if;
  return new;
end;
$$;

create trigger solicitudes_preparar before insert on public.solicitudes
  for each row execute function public.preparar_solicitud();

alter table public.solicitudes enable row level security;

grant insert on public.solicitudes to anon, authenticated;
grant select, update, delete on public.solicitudes to authenticated;
grant usage on sequence public.solicitudes_id_seq to anon, authenticated;

-- Enviar: solo para juegos visibles que no están en el local, y con el consentimiento marcado.
create policy "cualquiera envia solicitud" on public.solicitudes for insert to anon, authenticated
  with check (
    acepta
    and exists (select 1 from public.juegos j where j.id = juego_id and j.visible and not j.en_local)
  );
create policy "admin ve solicitudes" on public.solicitudes for select to authenticated using (public.es_admin());
create policy "admin edita solicitudes" on public.solicitudes for update to authenticated
  using (public.es_admin()) with check (public.es_admin());
create policy "admin borra solicitudes" on public.solicitudes for delete to authenticated using (public.es_admin());
