create table public.categorias (
  nombre text primary key,
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$')
);

-- Los datos de juego pueden faltar en lo importado de la tienda; un juego solo puede ser visible si está completo.
create table public.juegos (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  nombre text not null,
  jugadores_min smallint check (jugadores_min >= 1),
  jugadores_max smallint,
  duracion_min smallint check (duracion_min > 0),
  dificultad smallint check (dificultad between 1 and 5),
  edad_min smallint check (edad_min >= 0),
  categoria text references public.categorias (nombre) on update cascade,
  descripcion text,
  descripcion_tienda text,
  tips text[] not null default '{}',
  portada text,
  tienda_id bigint unique,
  url_tienda text,
  origen text not null default 'catalogo' check (origen in ('catalogo', 'tienda')),
  revisar boolean not null default false,
  visible boolean not null default false,
  creado timestamptz not null default now(),
  actualizado timestamptz not null default now(),
  check (jugadores_max >= jugadores_min),
  constraint visible_completo check (not visible or (
    jugadores_min is not null and jugadores_max is not null and duracion_min is not null
    and dificultad is not null and edad_min is not null and categoria is not null))
);

create index juegos_categoria_idx on public.juegos (categoria);
create index juegos_visible_idx on public.juegos (visible);

create function public.tocar_actualizado() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.actualizado = now();
  return new;
end;
$$;

create trigger juegos_actualizado before update on public.juegos
  for each row execute function public.tocar_actualizado();

create table public.admins (
  user_id uuid primary key references auth.users (id) on delete cascade
);

create function public.es_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

grant select on public.categorias, public.juegos to anon, authenticated;
grant insert, update, delete on public.categorias, public.juegos to authenticated;
grant usage on sequence public.juegos_id_seq to authenticated;
grant select on public.admins to authenticated;

alter table public.categorias enable row level security;
alter table public.juegos enable row level security;
alter table public.admins enable row level security;

create policy "lectura publica" on public.categorias for select to anon, authenticated using (true);
create policy "admin escribe" on public.categorias for all to authenticated
  using (public.es_admin()) with check (public.es_admin());

create policy "lectura publica de visibles" on public.juegos for select to anon, authenticated
  using (visible or public.es_admin());
create policy "admin inserta" on public.juegos for insert to authenticated with check (public.es_admin());
create policy "admin edita" on public.juegos for update to authenticated
  using (public.es_admin()) with check (public.es_admin());
create policy "admin borra" on public.juegos for delete to authenticated using (public.es_admin());

create policy "admin se ve" on public.admins for select to authenticated using (user_id = auth.uid());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portadas', 'portadas', true, 512000, array['image/webp', 'image/jpeg', 'image/png'])
on conflict (id) do nothing;

create policy "admin sube portadas" on storage.objects for insert to authenticated
  with check (bucket_id = 'portadas' and public.es_admin());
create policy "admin cambia portadas" on storage.objects for update to authenticated
  using (bucket_id = 'portadas' and public.es_admin());
create policy "admin borra portadas" on storage.objects for delete to authenticated
  using (bucket_id = 'portadas' and public.es_admin());
